# Generated by Django 5.1 on 2024-08-14 05:27

import Hotel_info.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to=Hotel_info.models.property_image_path),
        ),
    ]
