# Generated by Django 5.1 on 2024-08-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_info', '0003_alter_amenity_name_alter_location_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(blank=True, choices=[('country', 'Country'), ('state', 'State'), ('city', 'City')], max_length=500, null=True),
        ),
    ]
